import {StyleSheet} from 'react-native';
import {vh} from '../../../theme/units';
import {spacing} from '../../../theme/styles';
import {colors} from '../../../theme/colors';

export const styles = StyleSheet.create({
  profileContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.medium,
    paddingHorizontal: spacing.medium,
  },
  profileImage: {
    height: vh * 8,
    width: vh * 8,
    borderRadius: vh * 8,
  },
  profileWrap: {
    padding: spacing.small,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colors?.text.white,
    borderRadius: vh * 10,
    height: vh * 10,
    width: vh * 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  round: {
    borderRadius: 20,
    height: 10,
    width: 10,
    backgroundColor: colors?.background.green,
  },
  onlineStatusWrap: {
    flexDirection: 'row',
    gap: spacing.small,
    alignItems: 'center',
  },

  chatContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  messageContainer: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    marginBottom: 10,
    paddingHorizontal: spacing.large,
  },
  user1Container: {
    alignSelf: 'flex-end',
    flexDirection: 'row-reverse',
    gap: 10,
  },
  user2Container: {
    alignSelf: 'flex-start',
  },
  messageBubble: {
    padding: spacing.large,
    borderRadius: 16,
    maxWidth: '70%',
    backgroundColor: '#3f5263',
  },
  user1Bubble: {
    backgroundColor: '#3f5263',
  },
  user2Bubble: {
    backgroundColor: colors?.text.white,
  },

  userName: {
    marginBottom: 5,
    color: colors?.placeholder,
    // fontFamily: family?.semibold,
  },
  messageText: {
    fontSize: 16,
  },
  messageTime: {
    fontSize: 12,
    color: 'gray',
    marginTop: 5,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors?.border,
    padding: 10,
    backgroundColor: colors?.theme.white,
    borderRadius: 10,
    marginHorizontal: spacing.medium,
    marginBottom: spacing.medium,
  },
  textInput: {
    flex: 1,
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginRight: 10,
    color: colors?.placeholder,
  },
  sendButton: {
    backgroundColor: colors?.primary,
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  sendButtonText: {
    color: '#FFF',
    fontSize: 16,
  },
  triangle: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderTopWidth: 0,
    borderRightWidth: 20,
    borderBottomWidth: 18,
    borderLeftWidth: 0,
    borderTopColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#3f5263',
    borderLeftColor: 'transparent',
    position: 'absolute',
    bottom: 0,
    right: -10,
  },
  triangle2: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderTopWidth: 0,
    borderLeftWidth: 20,
    borderBottomWidth: 18,
    borderRightWidth: 0,
    borderTopColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: colors?.text.white,
    borderLeftColor: 'transparent',
    position: 'absolute',
    bottom: 0,
    left: -10,
  },
  customIconWrapper: {
    backgroundColor: colors?.white,
    borderRadius: 6,
    // height: WP('10'),
    // width: WP('10'),
    justifyContent: 'center',
    alignItems: 'center',
    // ...Shadows.shadow3,
  },
  customIconStyle: {
    // height: WP('6'),
    // width: WP('6'),
  },
  profileCustomIconWrapper: {
    backgroundColor: colors?.white,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    // ...Shadows.shadow3,
    overflow: 'hidden',
  },
  callWrapper: {
    paddingHorizontal: 10,
    // paddingVertical: WP('4'),
    backgroundColor: '#27AAE1',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderRadius: 6,
    alignItems: 'center',
  },
});
